package com.glodon.demo.mybatis.mappers;

import com.glodon.demo.mybatis.models.XYJH;

import java.util.List;

public interface XYJHMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_xyjh
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_xyjh
     *
     * @mbggenerated
     */
    int insert(XYJH record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_xyjh
     *
     * @mbggenerated
     */
    int insertSelective(XYJH record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_xyjh
     *
     * @mbggenerated
     */
    XYJH selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_xyjh
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(XYJH record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_xyjh
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(XYJH record);

    List<XYJH> selectAll();
}