package com.glodon.demo.mybatis.models;

import java.util.Date;

public class XYJH {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_xyjh.Id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_xyjh.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_xyjh.bizDate
     *
     * @mbggenerated
     */
    private Date bizdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_xyjh.jhlx
     *
     * @mbggenerated
     */
    private JHLX jhlx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_xyjh.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_xyjh.Id
     *
     * @return the value of tb_xyjh.Id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_xyjh.Id
     *
     * @param id the value for tb_xyjh.Id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_xyjh.code
     *
     * @return the value of tb_xyjh.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_xyjh.code
     *
     * @param code the value for tb_xyjh.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_xyjh.bizDate
     *
     * @return the value of tb_xyjh.bizDate
     *
     * @mbggenerated
     */
    public Date getBizdate() {
        return bizdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_xyjh.bizDate
     *
     * @param bizdate the value for tb_xyjh.bizDate
     *
     * @mbggenerated
     */
    public void setBizdate(Date bizdate) {
        this.bizdate = bizdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_xyjh.jhlx
     *
     * @return the value of tb_xyjh.jhlx
     *
     * @mbggenerated
     */
    public JHLX getJhlx() {
        return jhlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_xyjh.jhlx
     *
     * @param jhlx the value for tb_xyjh.jhlx
     *
     * @mbggenerated
     */
    public void setJhlx(JHLX jhlx) {
        this.jhlx = jhlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_xyjh.remark
     *
     * @return the value of tb_xyjh.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_xyjh.remark
     *
     * @param remark the value for tb_xyjh.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

}